# Generated by Django 3.2.9 on 2022-01-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jello', '0002_auto_20220118_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='jello.Product'),
        ),
    ]
