# Generated by Django 3.2.9 on 2022-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jello', '0003_customer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='customers', to='jello.Product'),
        ),
    ]
