# Generated by Django 3.2.9 on 2022-05-17 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jello', '0004_alter_customer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='house_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='Please enter a phonenumber like 0612345678', regex='^06\\d{8}')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_zipcode', message='Please enter a zipcode like: 1234AB or 1234ab', regex='\\d{4}[a-zA-Z]{2}')]),
        ),
    ]
